language: node_js

os:
- linux
- osx

install:
- curl -fL https://deno.land/x/install/install.sh | sh
- export PATH="$HOME/.deno/bin:$PATH"
- yarn install --ignore-engines

script:
- deno version
- yarn test
